---
- name: Install necessary packages
  apt:
    name:
      - avrdude
      - libssl-dev
      - libudev-dev
      - pkg-config
    update_cache: true
    state: present
  become: yes

- name: Check if cargo is installed
  stat:
    path: "$HOME/.cargo/bin/cargo"
  register: is_cargo_installed

- block:
  - name: 'Install cargo packages: "ravedude" and "cargo-generate"'
    command: "$HOME/.cargo/bin/cargo +stable install ravedude cargo-generate"
  when: is_cargo_installed.stat.exists
