---
- name: Get some package
  apt:
    name: ['fuse', 'git', 'python3-pip']
    state: present
    update_cache: true
    cache_valid_time: 86000
  become: yes

- name: Install nvim
  get_url:
    url: "https://github.com/neovim/neovim/releases/latest/download/nvim.appimage"
    dest: /usr/bin/nvim
    mode: "0755"
  become: yes

- name: Make nvim default editor
  alternatives:
    name: editor
    path: /usr/bin/nvim
  become: yes

- name: Symlink vim to nvim
  alternatives:
    name: vim
    path: /usr/bin/nvim
    priority: 100
  become: yes

- name: Create directories for nvim
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
  with_items:
    - "$HOME/.local/share/nvim/site/autoload"
    - "$HOME/.local/share/nvim/site/plugged"
    - "$HOME/.config/nvim"

- name: Install vimplug
  get_url:
    url: "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
    dest: "$HOME/.local/share/nvim/site/autoload/plug.vim"

- name: Add vimrc
  copy:
    src: vimrc
    dest: "$HOME/.vimrc"
    mode: "0644"

- name: Create basic init.vim
  copy:
    force: yes
    dest: "$HOME/.config/nvim/init.vim"
    content: |
      set runtimepath^=~/.vim runtimepath+=~/.vim/after
      let &packpath = &runtimepath
      source ~/.vimrc

- name: Install pynvim
  pip:
    name: pynvim
    executable: pip3
