---
- block:
  - name: Get some package
    apt:
      name: ['fuse', 'git', 'python3-pip', 'python3-venv']
      state: present
      update_cache: true
      cache_valid_time: 86000

  - name: Install nvim
    get_url:
      url: "https://github.com/neovim/neovim/releases/latest/download/nvim.appimage"
      dest: /usr/bin/nvim
      mode: "0755"

  - name: Make nvim default editor
    alternatives:
      name: editor
      path: /usr/bin/nvim

  - name: Symlink vim to nvim
    alternatives:
      name: vim
      link: /usr/bin/vim
      path: /usr/bin/nvim
      priority: 100
  become: yes

- name: Install needed python utilities
  pip:
    name: ['pynvim', 'jedi-language-server']
    executable: pip3

- name: Create directories for nvim
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
  with_items:
    - "{{ ansible_env['HOME'] }}/.local/share/nvim/site/autoload"
    - "{{ ansible_env['HOME'] }}/.local/share/nvim/site/plugged"
    - "{{ ansible_env['HOME'] }}/.config/nvim"

- name: Add vimrc
  copy:
    src: vimrc
    dest: "{{ ansible_env['HOME'] }}/.vimrc"
    mode: "0644"

- name: Create basic init.vim to forward to vimrc
  copy:
    force: yes
    dest: "{{ ansible_env['HOME'] }}/.config/nvim/init.vim"
    content: |
      set runtimepath^=~/.vim runtimepath+=~/.vim/after
      let &packpath = &runtimepath
      source {{ ansible_env['HOME'] }}/.vimrc
